### ISSUE TITLE
Test don't work

### ISSUE THREAD

**Issue by gtohagan** [callistaenterprise/blog-multitenancy#4]
Hi 
the tests on the Service layer don't appear to work.

If I run: `mvn '-Dtest=se.callista.blog.tenant_management.service.*.Test' test`
it produces an error relating to no tests found...

**Comment by beskow** [comment]
The tests in the service layer are integration tests, and hence are not executed during the 'test' lifecycle, but in the 'integration-test' lifecycle. Besides that, you have a syntax error in your '-Dtest=' class pattern. It is a class-matching pattern, not a regular expression. Hence the last part should be '.*Test' (remove the dot between the asterisk and Test).

 If you run `mvn '-Dtest=se.callista.blog.tenant_management.service.*Test' integration-test` it should work as expected.
